### ISSUE TITLE
Proper siege banner implementation

### ISSUE THREAD

**Issue by appgurueu** [Persistent-Kingdoms/persistent-factions#15]
The current implementation takes 10 min, no matter the distance of the closest team member.

**Comment by archfan7411** [comment]
Not changing this for several reasons:

- Factions should only claim what they can defend.
- Larger (member-wise) factions are now encouraged, to allow the defense of land and exploration.
- If you decide to go too far from your territory to defend it and yet still don't log off when an enemy joins, that's your fault; this is a comparatively hardcore server.
